#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

backg() {
	nitrogen --set-scale --save "$file"
	notify-send -u low -i info "Wallpaper Changed. $file" --icon=sxiv
}

sxiv_setbg() {
  # echo "file : $1"
  if [ -z "$1" ]
  then
    notify-send -i error -u critical "File is not supplied" --icon=sxiv
    exit 1
  fi
  nitrogen --set-zoom-fill --save "$1"
  notify-send -u low -i info "wallpaper changed" --icon=sxiv
}

sxiv_moveto() {
  # echo "$1"
  output_dir=$(ls -d $HOME/Pictures/* | dmenu -l 10 -p "Move To: ")
  # echo "$output_dir"
  if [ -z "$output_dir"];then
    return
  fi
  for f in $1;do
    mv "$f" "$output_dir"
  done
  # echo "🗸 Images Moved Successfully."
	notify-send -u low -i info "Image Moved to $output_dir" --icon=sxiv
}

export -f sxiv_moveto
export -f sxiv_setbg

case "$1" in
  "y")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard && notify-send "File path copied." --icon=sxiv ;;
  "Y")      while read file; do xclip -selection clipboard -target image/jpg "$file"; done ;;
  "e")      tr '\n' '\0' | xargs -0 gimp & ;;
  # "C-r")      while read file; do rawtherapee "$file" & done ;;
  "C-comma")  rotate 270 ;;
  "C-period") rotate  90 ;;
  "C-slash")  rotate 180 ;;
  "b") tr '\n' '\0' | xargs -0 -I {} bash -c 'sxiv_setbg {}' & ;;
  # "C-v") tr '\n' ' ' | xargs -0 -I {} bash -c 'sxiv_moveto {"$*"}' & ;;
  "v") tr '\n' ' ' | xargs -I {} bash -c 'sxiv_moveto "{}"' & ;;
esac
