" Characters from a to z
inoremap ,,aa 祿
inoremap ,,ab 綠
inoremap ,,ba 💡
inoremap ,,bb 🍻
inoremap ,,ca ☕
inoremap ,,cb 🥤
inoremap ,,da 🐶
inoremap ,,db 🦆
inoremap ,,ea 🐘
inoremap ,,eb 🦅
inoremap ,,fa 🦊
inoremap ,,fb 🔥
inoremap ,,ga 🐐
inoremap ,,gb 🔫
inoremap ,,ha 🐎
inoremap ,,hb 🐔
inoremap ,,ia 🗸
inoremap ,,ia ✅
inoremap ,,ib 🔖
inoremap ,,ja 🍺
inoremap ,,jb 🥂
inoremap ,,ka ⚾
inoremap ,,kb 🏉
inoremap ,,la 🦁
inoremap ,,lb 🔎
inoremap ,,ma 🐵
inoremap ,,mb 🙉
inoremap ,,n 🍺
inoremap ,,o 🧡
inoremap ,,p 🍐
inoremap ,,q ⛄
inoremap ,,r 🚀
inoremap ,,s 🌞
inoremap ,,t 🍅
inoremap ,,u ☔
inoremap ,,v 🚎
inoremap ,,w 🌊
inoremap ,,xa ❌
inoremap ,,xb 𐄂
inoremap ,,y ⛵
inoremap ,,z 🦓
