-- require("configs.global")
require("configs.options")
require("configs.colorizer")
require("configs.aero-statusline")
require("configs.bufferline")
require("configs.indentguides")
require("configs.peekup")
require("configs.treesitter")
require("configs.theme")
