
###############################################################
# This configuration file lets you
# - define new commands
# - change the shortcut or triggering keys of built-in verbs
# - change the colors
# - set default values for flags
#
# Configuration documentation is available at
#     https://dystroy.org/broot
###############################################################

###############################################################
# Default flags
# You can set up flags you want broot to start with by
# default, for example `default_flags="ihp"` if you usually want
# to see hidden and gitignored files and the permissions (then
# if you don't want the hidden files you can launch `br -H`)
# A popular flag is the `g` one which displays git related info.
#
default_flags = ""

###############################################################
# Verbs and shortcuts
# You can define your own commands which would be applied to
# the selection.
#
# Exemple 1: launching `tail -n` on the selected file (leaving broot)
# [[verbs]]
# name = "tail_lines"
# invocation = "tl {lines_count}"
# execution = "tail -f -n {lines_count} {file}"
#
# Exemple 2: creating a new file without leaving broot
# [[verbs]]
# name = "touch"
# invocation = "touch {new_file}"
# execution = "touch {directory}/{new_file}"
# leave_broot = false

# If $EDITOR isn't set on your computer, you should either set it using
#  something similar to
#   export EDITOR=/usr/bin/nvim
#  or just replace it with your editor of choice in the 'execution'
#  pattern.
# Example:
#  execution = "/usr/bin/nvim {file}"
[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "$EDITOR {file}"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
execution = "git diff {file}"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

# A popular set of shorctuts for going up and down:
#
[[verbs]]
key = "ctrl-j"
execution = ":line_down"


[[verbs]]
key = "ctrl-k"
execution = ":line_up"


[[verbs]]
key = "ctrl-h"
execution = ":page_up"


[[verbs]]
key = "ctrl-l"
execution = ":page_down"
#

# If you develop using git, you might like to often switch
# to the "git status" filter:
# [[verbs]]
# key = "ctrl-g"
# execution = ":toggle_git_status"

###############################################################
# Skin
# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values.
# Note that some of those colors might not correcly
# render on terminals with low capabilities.
#

[skin]
default = "rgb(236, 239, 244) rgb(46, 52, 64)"          # base0 base03
tree = "rgb(76, 86, 106) none"                        # base01 default
file = "rgb(216,222,233) none"                                     # default default
directory = "rgb(129, 161, 193) none bold"              # blue default bold
exe = "rgb(191, 97, 106) none"                            # red default
link = "rgb(136, 192, 208) none"                        # magenta default
pruning = "rgb(88, 110, 117) none italic"              # base01 default italic
perm__ = "rgb(88, 110, 117) none"                      # base01 default
perm_r = "none none"                                   # default default
perm_w = "none none"                                   # default default
perm_x = "none none"                                   # default default
owner = "rgb(88, 110, 117) none"                       # base01 default
group = "rgb(88, 110, 117) none"                       # base01 default
selected_line = "none rgb(76, 86, 106)"                  # default base02
char_match = "rgb(235, 203, 139) none underlined"        # green default underlined
file_error = "rgb(191, 97, 106) none italic"            # orange default italicb48ead
flag_label = "none none"                               # default default
flag_value = "rgb(163, 190, 140) none bold"              # yellow default bold
input = "rgb(236, 239, 244) none bold"                                    # default default
status_error = "rgb(203, 75, 22) rgb(46, 52, 64)"       # orange base02
status_job = "rgb(108, 113, 196) rgb(46, 52, 64) bold"  # violet base02 bold
status_normal = "none rgb(59, 66, 82)"                  # default base02
status_italic = "rgb(163, 190, 140) none bold"      # yellow base02
status_bold = "rgb(147, 161, 161) rgb(46, 52, 64) bold" # base1 base02 bold
status_code = "rgb(108, 113, 196) rgb(46, 52, 64)"      # violet base02
status_ellipsis = "none rgb(46, 52, 64)"                # default base02
scrollbar_track = "rgb(46, 52, 64) none"                # base02 default
scrollbar_thumb = "none none"                          # default default
help_paragraph = "none none"                           # default default
help_bold = "rgb(147, 161, 161) none bold"             # base1 default bold
help_italic = "rgb(147, 161, 161) none italic"         # base1 default italic
help_code = "rgb(147, 161, 161) rgb(46, 52, 64)"        # base1 base02
help_headers = "rgb(235, 203, 139) none"                 # yellow default

##################################################
#               SOLARIZED DARK
##################################################
# [skin]
# default = "rgb(131, 148, 150) rgb(0, 43, 54)"          # base0 base03
# tree = "rgb(88, 110, 117) none"                        # base01 default
# file = "none none"                                     # default default
# directory = "rgb(38, 139, 210) none bold"              # blue default bold
# exe = "rgb(211, 1, 2) none"                            # red default
# link = "rgb(211, 54, 130) none"                        # magenta default
# pruning = "rgb(88, 110, 117) none italic"              # base01 default italic
# perm__ = "rgb(88, 110, 117) none"                      # base01 default
# perm_r = "none none"                                   # default default
# perm_w = "none none"                                   # default default
# perm_x = "none none"                                   # default default
# owner = "rgb(88, 110, 117) none"                       # base01 default
# group = "rgb(88, 110, 117) none"                       # base01 default
# selected_line = "none rgb(7, 54, 66)"                  # default base02
# char_match = "rgb(133, 153, 0) none underlined"        # green default underlined
# file_error = "rgb(203, 75, 22) none italic"            # orange default italic
# flag_label = "none none"                               # default default
# flag_value = "rgb(181, 137, 0) none bold"              # yellow default bold
# input = "none none"                                    # default default
# status_error = "rgb(203, 75, 22) rgb(7, 54, 66)"       # orange base02
# status_job = "rgb(108, 113, 196) rgb(7, 54, 66) bold"  # violet base02 bold
# status_normal = "none rgb(7, 54, 66)"                  # default base02
# status_italic = "rgb(181, 137, 0) rgb(7, 54, 66)"      # yellow base02
# status_bold = "rgb(147, 161, 161) rgb(7, 54, 66) bold" # base1 base02 bold
# status_code = "rgb(108, 113, 196) rgb(7, 54, 66)"      # violet base02
# status_ellipsis = "none rgb(7, 54, 66)"                # default base02
# scrollbar_track = "rgb(7, 54, 66) none"                # base02 default
# scrollbar_thumb = "none none"                          # default default
# help_paragraph = "none none"                           # default default
# help_bold = "rgb(147, 161, 161) none bold"             # base1 default bold
# help_italic = "rgb(147, 161, 161) none italic"         # base1 default italic
# help_code = "rgb(147, 161, 161) rgb(7, 54, 66)"        # base1 base02
# help_headers = "rgb(181, 137, 0) none"                 # yellow default

# [skin]
# default = "gray(20) gray(1)"
# tree = "rgb(89, 73, 101) none"
# file = "gray(21) none"
# directory = "rgb(255, 152, 0) none bold"
# exe = "rgb(17, 164, 181) none"
# link = "Magenta none"
# pruning = "rgb(89, 73, 101) none Italic"
# perm__ = "gray(5) None"
# perm_r = "ansi(94) None"
# perm_w = "ansi(132) None"
# perm_x = "ansi(65) None"
# owner = "gray(12) none"
# group = "gray(12) none"
# selected_line = "none gray(3)"
# char_match = "yellow none"
# file_error = "Red none"
# flag_label = "gray(16) none"
# flag_value = "rgb(255, 152, 0) none bold"
# input = "White none"
# status_error = "Red gray(2)"
# status_job = "ansi(220) gray(5)"
# status_normal = "gray(20) gray(3)"
# status_italic = "rgb(255, 152, 0) None"
# status_bold = "rgb(255, 152, 0) None bold"
# status_code = "ansi(229) gray(5)"
# status_ellipsis = "gray(19) gray(1)"
# scrollbar_track = "rgb(80, 50, 0) none"
# scrollbar_thumb = "rgb(255, 187, 0) none"
# help_paragraph = "gray(20) none"
# help_bold = "rgb(255, 187, 0) none bold"
# help_italic = "Magenta rgb(30, 30, 40) italic"
# help_code = "gray(21) gray(3)"
# help_headers = "rgb(255, 187, 0) none"

# You may find other skins on
#  https://dystroy.org/broot/documentation/configuration/#colors
# for example a skin suitable for white backgrounds

